#!/usr/bin/env python

# public_deps='RPC_NDR_OXIDRESOLVER NDR_DCOM RPC_NDR_REMACT ndr_table DCOM_PROXY_DCOM DCOM'
bld.SAMBA_SUBSYSTEM('WMI',
	source='''
  wmicore.c
  wbemdata.c
  ../../../librpc/gen_ndr/dcom_p.c
  ../../../librpc/gen_ndr/wmi_p.c
        ''',
	public_deps='RPC_NDR_OXIDRESOLVER NDR_DCOM RPC_NDR_REMACT DCOM NDR_DCERPC dcerpc ndr'
	)


# bld.SAMBA_BINARY('wmic',
# 	source='tools/wmic.c',
# 	deps='popt samba-util WMI CMDLINE_S4 cmdline dcerpc ndr ndr-samba4'
# 	)


bld.SAMBA_BINARY('wmis',
	source='tools/wmis.c',
	deps='popt samba-util WMI CMDLINE_S4 cmdline dcerpc ndr ndr-samba4'
	)


bld.SAMBA_PYTHON('pywmi',
	source='wmi_wrap.c',
	public_deps='LIBCLI_SMB ndr samba-util samba-config WMI'
	)
